### PR TITLE
Support net6.0 and net8.0

### PR DESCRIPTION
**Pull request by ricaun**
This PR add support for NET Code 6.0 and NET Code 8.0.

The package gonna have an assembly for both versions.

Until [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/8.0.0) supports `net6.0` is a good idea to support as well.

### CODE REVIEW

**Comment by szilvaa** [comment]
> Until [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/8.0.0) supports net6.0 is a good idea to support as well.

I think that's a bit of presentation problem on the website. The package itself supports .net8:
https://nuget.info/packages/Microsoft.Extensions.DependencyInjection/8.0.0

**Comment by szilvaa** [comment]
I'm a bit reluctant to *add back* .net6 support 3 months before .net6 is out of support. People need to move on. The old package that supports .net6 is still available.

**Comment by ricaun** [comment]
> I'm a bit reluctant to _add back_ .net6 support 3 months before .net6 is out of support. People need to move on. The old package that supports .net6 is still available.

Rollback the version is annoying yes, but the version 4.0.1 has documentation and old version don't have that.

And the package gonna be ready when and if you update the **DependencyInjection** to version 9.0.0 that does not support `net6.0`, only `net8.0` and `net9.0`.

image

When creating a package I always create in the same/lowest version supported by the dependencies, and currently version `net6.0` is supported.

**Comment by szilvaa** [comment]
Can you describe the scenario where .net6 must be used for *new code* (the documentation is only relevant for the programmer writing new code)?

**Comment by ricaun** [comment]
> Can you describe the scenario where .net6 must be used for _new code_ (the documentation is only relevant for the programmer writing new code)?

The only scenario I use that package is inside some libraries I have, that is build in net6. 

I'm already glad that new docs was added and a Guthub Release exists.

I personally would never remove a target framework before the end of the year.

**Comment by szilvaa-adsk** [comment]
.net6 support ended.

**Pull request closed without merging**
